server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orderMngs/**, /selectItems/**, /selectOrders/**
        - id: Delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveryMngs/**, 
        - id: Stock
          uri: http://localhost:8083
          predicates:
            - Path=/stockMngs/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://order:8080
          predicates:
            - Path=/orderMngs/**, /selectItems/**, /selectOrders/**
        - id: Delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveryMngs/**, 
        - id: Stock
          uri: http://stock:8080
          predicates:
            - Path=/stockMngs/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
